#!/usr/bin/env python3

import pymongo

def create_or_use_database(database_name):
    # Connect to the MongoDB server
    client = pymongo.MongoClient("mongodb://localhost:27017/")

    # Use the specified database or create it if it doesn't exist
    db = client[database_name]

    # Confirm the switch to the specified database
    print(f'Switched to db {database_name}')

if __name__ == "__main__":
    # Specify the name of the database you want to create or use
    database_name = "my_db"

    create_or_use_database(database_name)
