#!/usr/bin/env python3

import pymongo

def insert_document(database_name, collection_name, document):
    client = pymongo.MongoClient("mongodb://localhost:27017/")

    db = client[database_name]

    collection = db[collection_name]

    result = collection.insert_one(document)

    print(result)

if __name__ == "__main__":
    database_name = "my_db"
    collection_name = "school"

    document = {"name": "Holberton school"}

    insert_document(database_name, collection_name, document)
